### ISSUE TITLE
ashcon's API doesn't support ?unsigned=false

### ISSUE THREAD

**Issue by bobhenl** [Electroid/mojang-api#82]
Hello, I wanted to use the Ashcon in the Citizens but I can't due to:
> ashcon's API doesn't support ?unsigned=false being appended to the URL, which sounds like a problem with their API setup
Dev reply

I tried using AshconAPII in citizens (latest build https://ci.citizensnpcs.co/job/Citizens2/) by replacing this:
```yml
general:
  authlib:
    # Search for gameprofiles using this URL
    profile-url: https://sessionserver.mojang.com/session/minecraft/profile/
```
in their config for this:
```yml
general:
  authlib:
    # Search for gameprofiles using this URL
    profile-url: https://api.ashcon.app/mojang/v2/user/
```
but it didn't work, even when the api should be similar to the mojang, no? What's wrong there please, how to fix?
